sudo: false
language: node_js
node_js:
  - 4
  - 5
  - 6

before_install:
  - npm install -g bower

before_script:
  - npm install -g grunt-cli
  - bower install

after_success:
  # Report coverage to codecov
  - ./script/send-coverage.sh
